services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  lint:
    build:
      context: .
      args:
        - DEV=true
    volumes:
      - .:/app
    environment:
      - PATH=/py/bin:$PATH
    command: >
      sh -c "/py/bin/flake8"  # Use full path to flake8