# Generated by Django 5.1.2 on 2024-11-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EcomProducts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="usd", max_length=3)),
                ("image_url", models.URLField(blank=True, null=True)),
                (
                    "payment_interval",
                    models.CharField(
                        choices=[
                            ("one_time", "One Time"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        default="one_time",
                        max_length=10,
                    ),
                ),
                ("quantity_available", models.PositiveIntegerField(default=1)),
                (
                    "trial_period_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
        ),
    ]
