"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path
#import dj_database_url





# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9xtqs4w&-#n=#5zj0=!6@58^7$_5=75v891nd@s+-edctkfyu#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'

ALLOWED_HOSTS = [
    '127.0.0.1',
  '.railway.app',

]


# Application definition

INSTALLED_APPS = [
    'dashboard.vristoDjango.apps.VristoDjangoConfig', 
    'dashboard.main.apps.MainConfig',
    'teachers.apps.TeachersConfig',
    'students.apps.StudentsConfig',
    'EcomProducts.apps.EcomproductsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
   # 'tailwindcss',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True



# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Directories to look for static files
# Define your static files base directory explicitly.
#  STATICFILES_BASE_DIR = BASE_DIR / "staticFiles"


# Define your static files base directory explicitly.
STATIC_URL = '/static/'

# Directories to look for static files
STATICFILES_DIRS = [
    BASE_DIR / "app/static",  # Your static files directory
]

# For production: centralize static files (only needed for deployment)
STATIC_ROOT = BASE_DIR / "staticfiles_collected"

# output sources for python manage.py collectstatic

#STATIC_ROOT = BASE_DIR.parent / "local-cdn"

# Add this if you haven't already
#STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
#MEDIA_ROOT = os.path.join(BASE_DIR 'pictures' )
#MEDIA_URL = '/pictures/'




LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'  

#NEON POSTGRESQL

# Add these at the top of your settings.py
